### PR TITLE
Use the `name` in project.yml as the name for the gemspec

### PR DESCRIPTION
**Pull request by timriley**
This allows projects to have differing gem and repo names

The specific use case here is the renaming of dry-view to hanami-view while it still situated in the dry-rb/dry-view repo on GitHub. Even after that repo is moved to hanami/view, we'll need this feature since the repo name will not identically match the gem name ("view" vs "hanami-view").

### CODE REVIEW

**Comment by timriley** [comment]
@solnic any idea how I can actually test this? 😇

**Comment by solnic** [comment]
~@timriley we have `dry-rb/testing` project that you can use. You need to merge this into master and trigger its sync manually via `ossy gh w dry-rb/testing sync_configs`.~

👇 👇

**Comment by solnic** [comment]
@timriley oh wait what am I saying - by merging to master you will trigger sync across all projects 😆 so, you can leave only `testing` in `projects` file and once you know it works as expected, re-add all projects again (by just reverting the commit that removed them).

**Comment by timriley** [comment]
@solnic OK! Thanks, I'll do this. Are you suggesting this should be all be done on `master`, btw?

i.e. 

1. I add a commit to this branch that removes all projects but dry-rb/testing
2. I merge this PR to master
3. I test/iterate/etc.
4. I revert the commit from (1) (i.e. re-add all the other projects again)

Does that sound right?

**Comment by solnic** [comment]
@timriley at this stage I wouldn't even bother with PRs to be honest. Just turn on the testing mode in master (by removing all projects except `testing`), do your thing, revert testing mode.

**Comment by timriley** [comment]
@solnic Thanks for the pointers! I'll go through this process now.

**Pull request merged**
